--
-- PostgreSQL database dump
--

\restrict RYDl2OFcSLHGpci0ChUlApYCxNmmhP2HEIrHTE2l1kEwd5nbsTxnIBUJ0G4JcFv

-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: tbl_cart; Type: TABLE; Schema: public; Owner: ecommerce
--

CREATE TABLE public.tbl_cart (
    id smallint NOT NULL,
    created_at date NOT NULL,
    updated_at date,
    user_id integer
);


ALTER TABLE public.tbl_cart OWNER TO ecommerce;

--
-- Name: tbl_cart_id_seq; Type: SEQUENCE; Schema: public; Owner: ecommerce
--

ALTER TABLE public.tbl_cart ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbl_cart_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_cart_item; Type: TABLE; Schema: public; Owner: ecommerce
--

CREATE TABLE public.tbl_cart_item (
    id smallint NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(10,2) NOT NULL,
    cart_id smallint,
    product_id integer
);


ALTER TABLE public.tbl_cart_item OWNER TO ecommerce;

--
-- Name: tbl_cart_item_id_seq; Type: SEQUENCE; Schema: public; Owner: ecommerce
--

ALTER TABLE public.tbl_cart_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbl_cart_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_category; Type: TABLE; Schema: public; Owner: ecommerce
--

CREATE TABLE public.tbl_category (
    id smallint NOT NULL,
    created_at date NOT NULL,
    updated_at date,
    description character varying(255) NOT NULL,
    name character varying(50) NOT NULL,
    status boolean
);


ALTER TABLE public.tbl_category OWNER TO ecommerce;

--
-- Name: tbl_category_id_seq; Type: SEQUENCE; Schema: public; Owner: ecommerce
--

ALTER TABLE public.tbl_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbl_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_order; Type: TABLE; Schema: public; Owner: ecommerce
--

CREATE TABLE public.tbl_order (
    id smallint NOT NULL,
    created_at date NOT NULL,
    updated_at date,
    cancelled_at timestamp(6) with time zone,
    note character varying(255) NOT NULL,
    order_code character varying(30) NOT NULL,
    order_status character varying(255) NOT NULL,
    payment_method character varying(30) NOT NULL,
    ship_order_line character varying(255),
    ship_city character varying(100),
    ship_country character varying(10),
    ship_full_name character varying(100),
    ship_phone character varying(255),
    shipping_fee numeric(10,2) NOT NULL,
    subtotal numeric(10,2) NOT NULL,
    total_amount numeric(10,2) NOT NULL,
    tracking_numer character varying(255),
    user_id integer,
    CONSTRAINT tbl_order_order_status_check CHECK (((order_status)::text = ANY ((ARRAY['PENDING_PAYMENT'::character varying, 'PENDING'::character varying, 'PROCESSING'::character varying, 'SHIPPED'::character varying, 'DELIVERED'::character varying, 'CANCELLED'::character varying, 'REFUNDED'::character varying])::text[]))),
    CONSTRAINT tbl_order_payment_method_check CHECK (((payment_method)::text = ANY ((ARRAY['CASH_0N_DELIVERY'::character varying, 'KHQR_BAKONG'::character varying])::text[])))
);


ALTER TABLE public.tbl_order OWNER TO ecommerce;

--
-- Name: tbl_order_id_seq; Type: SEQUENCE; Schema: public; Owner: ecommerce
--

ALTER TABLE public.tbl_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbl_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_order_item; Type: TABLE; Schema: public; Owner: ecommerce
--

CREATE TABLE public.tbl_order_item (
    id smallint NOT NULL,
    created_at date NOT NULL,
    updated_at date,
    discount_rate real NOT NULL,
    final_price numeric(10,2) NOT NULL,
    product_image character varying(255),
    product_name character varying(100) NOT NULL,
    quantity integer NOT NULL,
    subtotal numeric(10,2) NOT NULL,
    unit_price numeric(10,2) NOT NULL,
    order_id smallint,
    product_id integer
);


ALTER TABLE public.tbl_order_item OWNER TO ecommerce;

--
-- Name: tbl_order_item_id_seq; Type: SEQUENCE; Schema: public; Owner: ecommerce
--

ALTER TABLE public.tbl_order_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbl_order_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_payment; Type: TABLE; Schema: public; Owner: ecommerce
--

CREATE TABLE public.tbl_payment (
    id integer NOT NULL,
    created_at date NOT NULL,
    updated_at date,
    amount numeric(10,2) NOT NULL,
    currency smallint,
    deep_link character varying(255),
    expires_at timestamp(6) with time zone,
    md5 character varying(500) NOT NULL,
    payment_method character varying(255) NOT NULL,
    paid_at timestamp(6) with time zone,
    payment_status smallint NOT NULL,
    qr_string character varying(500) NOT NULL,
    transaction_id character varying(50) NOT NULL,
    webhook_payload text,
    order_id smallint,
    CONSTRAINT tbl_payment_currency_check CHECK (((currency >= 0) AND (currency <= 1))),
    CONSTRAINT tbl_payment_payment_method_check CHECK (((payment_method)::text = ANY ((ARRAY['CASH_0N_DELIVERY'::character varying, 'KHQR_BAKONG'::character varying])::text[]))),
    CONSTRAINT tbl_payment_payment_status_check CHECK (((payment_status >= 0) AND (payment_status <= 3)))
);


ALTER TABLE public.tbl_payment OWNER TO ecommerce;

--
-- Name: tbl_payment_id_seq; Type: SEQUENCE; Schema: public; Owner: ecommerce
--

ALTER TABLE public.tbl_payment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbl_payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_product; Type: TABLE; Schema: public; Owner: ecommerce
--

CREATE TABLE public.tbl_product (
    id integer NOT NULL,
    created_at date NOT NULL,
    updated_at date,
    description character varying(500) NOT NULL,
    discount real,
    name character varying(50) NOT NULL,
    price double precision NOT NULL,
    quantity integer NOT NULL,
    category_id smallint,
    user_id integer
);


ALTER TABLE public.tbl_product OWNER TO ecommerce;

--
-- Name: tbl_product_id_seq; Type: SEQUENCE; Schema: public; Owner: ecommerce
--

ALTER TABLE public.tbl_product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbl_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_product_image; Type: TABLE; Schema: public; Owner: ecommerce
--

CREATE TABLE public.tbl_product_image (
    product_id integer NOT NULL,
    image_url character varying(255)
);


ALTER TABLE public.tbl_product_image OWNER TO ecommerce;

--
-- Name: tbl_refresh_token; Type: TABLE; Schema: public; Owner: ecommerce
--

CREATE TABLE public.tbl_refresh_token (
    id integer NOT NULL,
    created_at date NOT NULL,
    updated_at date,
    expiry_data timestamp(6) with time zone NOT NULL,
    token character varying(255) NOT NULL,
    user_id integer
);


ALTER TABLE public.tbl_refresh_token OWNER TO ecommerce;

--
-- Name: tbl_refresh_token_id_seq; Type: SEQUENCE; Schema: public; Owner: ecommerce
--

ALTER TABLE public.tbl_refresh_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbl_refresh_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_shipping_address; Type: TABLE; Schema: public; Owner: ecommerce
--

CREATE TABLE public.tbl_shipping_address (
    id smallint NOT NULL,
    created_at date NOT NULL,
    updated_at date,
    address_line character varying(255),
    city character varying(255),
    country character varying(255),
    full_name character varying(255) NOT NULL,
    is_default boolean,
    shipping_note character varying(255),
    phone character varying(255) NOT NULL,
    province character varying(255),
    user_id integer
);


ALTER TABLE public.tbl_shipping_address OWNER TO ecommerce;

--
-- Name: tbl_shipping_address_id_seq; Type: SEQUENCE; Schema: public; Owner: ecommerce
--

ALTER TABLE public.tbl_shipping_address ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbl_shipping_address_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_user; Type: TABLE; Schema: public; Owner: ecommerce
--

CREATE TABLE public.tbl_user (
    id integer NOT NULL,
    created_at date NOT NULL,
    updated_at date,
    bio character varying(255),
    date_of_birth character varying(255),
    email character varying(50) NOT NULL,
    full_name character varying(50) NOT NULL,
    password character varying(255) NOT NULL,
    phone_number character varying(20),
    reset_opt character varying(6),
    reset_opt_expire_at bigint,
    roles smallint[] NOT NULL,
    status boolean NOT NULL
);


ALTER TABLE public.tbl_user OWNER TO ecommerce;

--
-- Name: tbl_user_id_seq; Type: SEQUENCE; Schema: public; Owner: ecommerce
--

ALTER TABLE public.tbl_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbl_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: tbl_cart; Type: TABLE DATA; Schema: public; Owner: ecommerce
--

COPY public.tbl_cart (id, created_at, updated_at, user_id) FROM stdin;
\.


--
-- Data for Name: tbl_cart_item; Type: TABLE DATA; Schema: public; Owner: ecommerce
--

COPY public.tbl_cart_item (id, quantity, unit_price, cart_id, product_id) FROM stdin;
\.


--
-- Data for Name: tbl_category; Type: TABLE DATA; Schema: public; Owner: ecommerce
--

COPY public.tbl_category (id, created_at, updated_at, description, name, status) FROM stdin;
\.


--
-- Data for Name: tbl_order; Type: TABLE DATA; Schema: public; Owner: ecommerce
--

COPY public.tbl_order (id, created_at, updated_at, cancelled_at, note, order_code, order_status, payment_method, ship_order_line, ship_city, ship_country, ship_full_name, ship_phone, shipping_fee, subtotal, total_amount, tracking_numer, user_id) FROM stdin;
\.


--
-- Data for Name: tbl_order_item; Type: TABLE DATA; Schema: public; Owner: ecommerce
--

COPY public.tbl_order_item (id, created_at, updated_at, discount_rate, final_price, product_image, product_name, quantity, subtotal, unit_price, order_id, product_id) FROM stdin;
\.


--
-- Data for Name: tbl_payment; Type: TABLE DATA; Schema: public; Owner: ecommerce
--

COPY public.tbl_payment (id, created_at, updated_at, amount, currency, deep_link, expires_at, md5, payment_method, paid_at, payment_status, qr_string, transaction_id, webhook_payload, order_id) FROM stdin;
\.


--
-- Data for Name: tbl_product; Type: TABLE DATA; Schema: public; Owner: ecommerce
--

COPY public.tbl_product (id, created_at, updated_at, description, discount, name, price, quantity, category_id, user_id) FROM stdin;
\.


--
-- Data for Name: tbl_product_image; Type: TABLE DATA; Schema: public; Owner: ecommerce
--

COPY public.tbl_product_image (product_id, image_url) FROM stdin;
\.


--
-- Data for Name: tbl_refresh_token; Type: TABLE DATA; Schema: public; Owner: ecommerce
--

COPY public.tbl_refresh_token (id, created_at, updated_at, expiry_data, token, user_id) FROM stdin;
1	2026-06-29	2026-06-29	2026-07-29 10:50:40.339647+00	eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJDaGFtcmV1biBWaXJhIiwiaWF0IjoxNzgyNzMwMjQwLCJleHAiOjE3ODM3MzAyNDB9.t5lKonE2zUGKOw_N6xRJav17CEUEy344BfZ94ZuBnic8E7BjY5LmdCQNaO2RfSegJdYINnxI0rwNIHnT4lHvTA	1
\.


--
-- Data for Name: tbl_shipping_address; Type: TABLE DATA; Schema: public; Owner: ecommerce
--

COPY public.tbl_shipping_address (id, created_at, updated_at, address_line, city, country, full_name, is_default, shipping_note, phone, province, user_id) FROM stdin;
\.


--
-- Data for Name: tbl_user; Type: TABLE DATA; Schema: public; Owner: ecommerce
--

COPY public.tbl_user (id, created_at, updated_at, bio, date_of_birth, email, full_name, password, phone_number, reset_opt, reset_opt_expire_at, roles, status) FROM stdin;
1	2026-06-29	2026-06-29	\N	\N	virachamreun@gmail.com	Chamreun Vira	$2a$10$hLnw3JQquhbkUNKOoNJ4iuHU5IMKb4axbScg9UARJNh6cMvcJMvBK	\N	\N	\N	{1}	t
\.


--
-- Name: tbl_cart_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ecommerce
--

SELECT pg_catalog.setval('public.tbl_cart_id_seq', 1, false);


--
-- Name: tbl_cart_item_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ecommerce
--

SELECT pg_catalog.setval('public.tbl_cart_item_id_seq', 1, false);


--
-- Name: tbl_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ecommerce
--

SELECT pg_catalog.setval('public.tbl_category_id_seq', 1, false);


--
-- Name: tbl_order_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ecommerce
--

SELECT pg_catalog.setval('public.tbl_order_id_seq', 1, false);


--
-- Name: tbl_order_item_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ecommerce
--

SELECT pg_catalog.setval('public.tbl_order_item_id_seq', 1, false);


--
-- Name: tbl_payment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ecommerce
--

SELECT pg_catalog.setval('public.tbl_payment_id_seq', 1, false);


--
-- Name: tbl_product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ecommerce
--

SELECT pg_catalog.setval('public.tbl_product_id_seq', 10, true);


--
-- Name: tbl_refresh_token_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ecommerce
--

SELECT pg_catalog.setval('public.tbl_refresh_token_id_seq', 1, true);


--
-- Name: tbl_shipping_address_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ecommerce
--

SELECT pg_catalog.setval('public.tbl_shipping_address_id_seq', 1, false);


--
-- Name: tbl_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ecommerce
--

SELECT pg_catalog.setval('public.tbl_user_id_seq', 1, true);


--
-- Name: tbl_cart_item tbl_cart_item_pkey; Type: CONSTRAINT; Schema: public; Owner: ecommerce
--

ALTER TABLE ONLY public.tbl_cart_item
    ADD CONSTRAINT tbl_cart_item_pkey PRIMARY KEY (id);


--
-- Name: tbl_cart tbl_cart_pkey; Type: CONSTRAINT; Schema: public; Owner: ecommerce
--

ALTER TABLE ONLY public.tbl_cart
    ADD CONSTRAINT tbl_cart_pkey PRIMARY KEY (id);


--
-- Name: tbl_category tbl_category_pkey; Type: CONSTRAINT; Schema: public; Owner: ecommerce
--

ALTER TABLE ONLY public.tbl_category
    ADD CONSTRAINT tbl_category_pkey PRIMARY KEY (id);


--
-- Name: tbl_order_item tbl_order_item_pkey; Type: CONSTRAINT; Schema: public; Owner: ecommerce
--

ALTER TABLE ONLY public.tbl_order_item
    ADD CONSTRAINT tbl_order_item_pkey PRIMARY KEY (id);


--
-- Name: tbl_order tbl_order_pkey; Type: CONSTRAINT; Schema: public; Owner: ecommerce
--

ALTER TABLE ONLY public.tbl_order
    ADD CONSTRAINT tbl_order_pkey PRIMARY KEY (id);


--
-- Name: tbl_payment tbl_payment_pkey; Type: CONSTRAINT; Schema: public; Owner: ecommerce
--

ALTER TABLE ONLY public.tbl_payment
    ADD CONSTRAINT tbl_payment_pkey PRIMARY KEY (id);


--
-- Name: tbl_product tbl_product_pkey; Type: CONSTRAINT; Schema: public; Owner: ecommerce
--

ALTER TABLE ONLY public.tbl_product
    ADD CONSTRAINT tbl_product_pkey PRIMARY KEY (id);


--
-- Name: tbl_refresh_token tbl_refresh_token_pkey; Type: CONSTRAINT; Schema: public; Owner: ecommerce
--

ALTER TABLE ONLY public.tbl_refresh_token
    ADD CONSTRAINT tbl_refresh_token_pkey PRIMARY KEY (id);


--
-- Name: tbl_shipping_address tbl_shipping_address_pkey; Type: CONSTRAINT; Schema: public; Owner: ecommerce
--

ALTER TABLE ONLY public.tbl_shipping_address
    ADD CONSTRAINT tbl_shipping_address_pkey PRIMARY KEY (id);


--
-- Name: tbl_user tbl_user_pkey; Type: CONSTRAINT; Schema: public; Owner: ecommerce
--

ALTER TABLE ONLY public.tbl_user
    ADD CONSTRAINT tbl_user_pkey PRIMARY KEY (id);


--
-- Name: tbl_category uk8f25rdca1qev4kqtyrxwsx0k8; Type: CONSTRAINT; Schema: public; Owner: ecommerce
--

ALTER TABLE ONLY public.tbl_category
    ADD CONSTRAINT uk8f25rdca1qev4kqtyrxwsx0k8 UNIQUE (name);


--
-- Name: tbl_payment ukbh50w3ob89d7n68ip03mpdldo; Type: CONSTRAINT; Schema: public; Owner: ecommerce
--

ALTER TABLE ONLY public.tbl_payment
    ADD CONSTRAINT ukbh50w3ob89d7n68ip03mpdldo UNIQUE (transaction_id);


--
-- Name: tbl_cart ukeymp5kbfgooc31l260hr63vox; Type: CONSTRAINT; Schema: public; Owner: ecommerce
--

ALTER TABLE ONLY public.tbl_cart
    ADD CONSTRAINT ukeymp5kbfgooc31l260hr63vox UNIQUE (user_id);


--
-- Name: tbl_payment ukf32395wa9xoapy5h23u5d643p; Type: CONSTRAINT; Schema: public; Owner: ecommerce
--

ALTER TABLE ONLY public.tbl_payment
    ADD CONSTRAINT ukf32395wa9xoapy5h23u5d643p UNIQUE (order_id);


--
-- Name: tbl_refresh_token ukmpgc5sdw3koqkok2ufdhkh7wx; Type: CONSTRAINT; Schema: public; Owner: ecommerce
--

ALTER TABLE ONLY public.tbl_refresh_token
    ADD CONSTRAINT ukmpgc5sdw3koqkok2ufdhkh7wx UNIQUE (user_id);


--
-- Name: tbl_user uknpn1wf1yu1g5rjohbek375pp1; Type: CONSTRAINT; Schema: public; Owner: ecommerce
--

ALTER TABLE ONLY public.tbl_user
    ADD CONSTRAINT uknpn1wf1yu1g5rjohbek375pp1 UNIQUE (email);


--
-- Name: tbl_order ukt91aupbg9yjoyjtx66qo1n0mq; Type: CONSTRAINT; Schema: public; Owner: ecommerce
--

ALTER TABLE ONLY public.tbl_order
    ADD CONSTRAINT ukt91aupbg9yjoyjtx66qo1n0mq UNIQUE (order_code);


--
-- Name: tbl_order_item fk1oy9x003q55eqmuiv0y8a15e; Type: FK CONSTRAINT; Schema: public; Owner: ecommerce
--

ALTER TABLE ONLY public.tbl_order_item
    ADD CONSTRAINT fk1oy9x003q55eqmuiv0y8a15e FOREIGN KEY (product_id) REFERENCES public.tbl_product(id);


--
-- Name: tbl_cart_item fk84umwt3ihkiggf03us5gq116j; Type: FK CONSTRAINT; Schema: public; Owner: ecommerce
--

ALTER TABLE ONLY public.tbl_cart_item
    ADD CONSTRAINT fk84umwt3ihkiggf03us5gq116j FOREIGN KEY (product_id) REFERENCES public.tbl_product(id);


--
-- Name: tbl_payment fkac54xp3r2r3m9datds9351ric; Type: FK CONSTRAINT; Schema: public; Owner: ecommerce
--

ALTER TABLE ONLY public.tbl_payment
    ADD CONSTRAINT fkac54xp3r2r3m9datds9351ric FOREIGN KEY (order_id) REFERENCES public.tbl_order(id);


--
-- Name: tbl_product fkbcejabdqv6xehq9386c69job; Type: FK CONSTRAINT; Schema: public; Owner: ecommerce
--

ALTER TABLE ONLY public.tbl_product
    ADD CONSTRAINT fkbcejabdqv6xehq9386c69job FOREIGN KEY (user_id) REFERENCES public.tbl_user(id);


--
-- Name: tbl_product fkfq7110lh85cseoy13cgni7pet; Type: FK CONSTRAINT; Schema: public; Owner: ecommerce
--

ALTER TABLE ONLY public.tbl_product
    ADD CONSTRAINT fkfq7110lh85cseoy13cgni7pet FOREIGN KEY (category_id) REFERENCES public.tbl_category(id);


--
-- Name: tbl_cart_item fkhaw0aw4g8s9icxekpl4oi715a; Type: FK CONSTRAINT; Schema: public; Owner: ecommerce
--

ALTER TABLE ONLY public.tbl_cart_item
    ADD CONSTRAINT fkhaw0aw4g8s9icxekpl4oi715a FOREIGN KEY (cart_id) REFERENCES public.tbl_cart(id);


--
-- Name: tbl_cart fkhv6grtjnmtoylt2yyt4wmqtf3; Type: FK CONSTRAINT; Schema: public; Owner: ecommerce
--

ALTER TABLE ONLY public.tbl_cart
    ADD CONSTRAINT fkhv6grtjnmtoylt2yyt4wmqtf3 FOREIGN KEY (user_id) REFERENCES public.tbl_user(id);


--
-- Name: tbl_order fkhyolniflkctr0p6bp4t8me9vj; Type: FK CONSTRAINT; Schema: public; Owner: ecommerce
--

ALTER TABLE ONLY public.tbl_order
    ADD CONSTRAINT fkhyolniflkctr0p6bp4t8me9vj FOREIGN KEY (user_id) REFERENCES public.tbl_user(id);


--
-- Name: tbl_refresh_token fkjy4oisva8l5wptq3sslq6x5d1; Type: FK CONSTRAINT; Schema: public; Owner: ecommerce
--

ALTER TABLE ONLY public.tbl_refresh_token
    ADD CONSTRAINT fkjy4oisva8l5wptq3sslq6x5d1 FOREIGN KEY (user_id) REFERENCES public.tbl_user(id);


--
-- Name: tbl_shipping_address fkm1mg4tlnovh8r80doh7awhbv7; Type: FK CONSTRAINT; Schema: public; Owner: ecommerce
--

ALTER TABLE ONLY public.tbl_shipping_address
    ADD CONSTRAINT fkm1mg4tlnovh8r80doh7awhbv7 FOREIGN KEY (user_id) REFERENCES public.tbl_user(id);


--
-- Name: tbl_order_item fkmkqpajkg6p2wq4owcv1v08pc5; Type: FK CONSTRAINT; Schema: public; Owner: ecommerce
--

ALTER TABLE ONLY public.tbl_order_item
    ADD CONSTRAINT fkmkqpajkg6p2wq4owcv1v08pc5 FOREIGN KEY (order_id) REFERENCES public.tbl_order(id);


--
-- Name: tbl_product_image fkmoh9bwnhu81rx27vxwxbg80up; Type: FK CONSTRAINT; Schema: public; Owner: ecommerce
--

ALTER TABLE ONLY public.tbl_product_image
    ADD CONSTRAINT fkmoh9bwnhu81rx27vxwxbg80up FOREIGN KEY (product_id) REFERENCES public.tbl_product(id);


--
-- PostgreSQL database dump complete
--

\unrestrict RYDl2OFcSLHGpci0ChUlApYCxNmmhP2HEIrHTE2l1kEwd5nbsTxnIBUJ0G4JcFv

